name: Docker Scout

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'  # Daily

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build image
        uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # v6
        with:
          targets: ci
          load: true

      - name: Docker Scout CVE scan
        uses: docker/scout-action@67eb1afe777f570c3847f4e4045da4e691a7ac44 # v1.16.1
        with:
          command: cves
          image: phpbu:ci
          sarif-file: scout-results.sarif
          summary: true

      - name: Upload Scout results
        uses: github/codeql-action/upload-sarif@4bdb89f48054571735e3792627da6195c57459e2 # v3
        if: always()
        with:
          sarif_file: scout-results.sarif

      - name: Docker Scout recommendations
        if: github.event_name == 'pull_request'
        uses: docker/scout-action@67eb1afe777f570c3847f4e4045da4e691a7ac44 # v1.16.1
        with:
          command: recommendations
          image: phpbu:ci
          only-fixed: true
